### ISSUE TITLE
paper-ripple seems to create a separate layer for each element when it is instantiated

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/paper-ripple#14]
This seems to be causing slow compositing on pages where there are multiple paper-ripples, such as lists where there is a ripple on each item when tapped.

**Comment by cdata** [comment]
Daniel showed this to me - I'll take a look at it.

**Comment by tjsavage** [comment]
:+1: thanks!

**Comment by firasdib** [comment]
Status on this?

**Comment by cdata** [comment]
Sorry, this should have been fixed in https://github.com/PolymerElements/paper-ripple/pull/19. Please re-open if it is still happening for you!

**Comment by firasdib** [comment]
@cdata My issue might be something else. I have a bunch of `<paper-ripple>` in a list (in every `li`-element) and when I click the element, the ripple spreads out over the entire website. Even if the parent is `position: relative;`. Is this normal?
