### ISSUE TITLE
ripple effect leaking out from local dom to parent of custom element

### ISSUE THREAD

**Issue by ranjeet-choudhary** [PolymerElements/paper-ripple#31]
```
  <template>
    <paper-item on-click="_toggle" class="collapse-menu">
      <span class="flex">{{data.name}}</span>
      <iron-icon icon="{{collapseMenuIcon}}"></iron-icon>
    </paper-item>
    <iron-collapse opened="{{data.opened}}" id="collapse">
      <div class="collapse-content">
        <more-route-selector>
          <paper-menu>
            <template is="dom-repeat" items="[[data.list]]">
              <paper-item id$="[[item.route]]" route$="[[item.route]]">
                <iron-icon icon="[[item.icon]]"></iron-icon>
                <span>[[item.name]]</span>
                <paper-ripple></paper-ripple>
              </paper-item>
            </template>
          </paper-menu>
        </more-route-selector>
      </div>
    </iron-collapse>
  </template>
```
I'm trying to add ripple effect to paper-item but its leaking to entire custom element as well as parent element

**Comment by Compufreak345** [comment]
I've got the same issue. A workaround is putting a "style='position:relative'" on the surrounding element. Not always appropriate and quite strange, but it worked for me.

**Comment by ranjeet-choudhary** [comment]
@Compufreak345 thanks, working fine after adding "style='position:relative'"

**Comment by motss** [comment]
@Compufreak345 Thanks a lot, wondering how you came up with this workaround. Well done! It just worked!

**Comment by Compufreak345** [comment]
@motss It was by accident ;) I had one element with relative layout in my design - that was the one where my first ripple stopped. After a second ripple did not stop anywhere I just compared the style of this one and its parents ;) After like an hour with trial and error I got the right one :0

**Comment by Sajgoniarz** [comment]
@Compufreak345 Thx, it was really annoying. In my case I even selected another menu items...

**Comment by ebidel** [comment]
Added this note to the docs so it's more clear.

https://github.com/PolymerElements/paper-ripple/blob/master/paper-ripple.html#L20
