### ISSUE TITLE
paper-ripple buggy with paper-menu

### ISSUE THREAD

**Issue by toyongbanatero** [PolymerElements/paper-ripple#32]
I am writing code with a paper-icon-item and tried to add a paper-ripple with each paper-menu item and the effects were pretty bad.

Here's the part where it's all messed up and I can confirm that it persists even with just these lines.

```html
<paper-menu selected="0">
    <paper-icon-item>
        <iron-icon icon="icons:home" item-icon></iron-icon>Home<paper-ripple></paper-ripple>
    </paper-icon-item>
    <paper-icon-item>
        <iron-icon icon="icons:account-box" item-icon></iron-icon>Login<paper-ripple></paper-ripple>
    </paper-icon-item>
    <paper-icon-item>
        <iron-icon icon="social:person-add" item-icon></iron-icon>Register<paper-ripple></paper-ripple>
    </paper-icon-item>
</paper-menu>
```

I don't know if it was just an error in my part, but if it is please correct me. Thanks!

**Comment by fiws** [comment]
Try adding a `position: relative` to the `paper-icon-item`s

**Comment by toyongbanatero** [comment]
Hey. That solves it.
I'm sorry. It was not in the docs (AFAIK) so I haven't tried that solution.
Thanks!
Should I close this now?

**Comment by fiws** [comment]
Maybe this should be noted somewhere. I also only discovered this by trail and error.
