### ISSUE TITLE
parentNode is undefined - IE/Firefox

### ISSUE THREAD

**Issue by mcarey1590** [PolymerElements/paper-ripple#35]
i traced it to 
```
if (this.parentNode.nodeType == 11) { // DOCUMENT_FRAGMENT_NODE
          target = ownerRoot.host;
        } else {
          target = this.parentNode;
        }
```

should be 

```
var parentNode = Polymer.dom(this.parentNode);
if (parentNode.nodeType == 11) { // DOCUMENT_FRAGMENT_NODE
          target = ownerRoot.host;
        } else {
          target = parentNode;
        }
...

**Comment by robrez** [comment]
Seeing this as well.

Should the above be `var parentNode = Polymer.dom(this).parentNode;`, instead?

Making the changes outlined above, I start getting a couple of other various errors relating to either
- target being null
- target not supporting "addEventListener"

... which seems odd - I'm not sure if there's a third potential target here that would be more appropriate.

I wonder if the event bindings that occur in attached() need to be executed via async() to be more like the old "domReady" callback.

**Comment by manfield** [comment]
I encountered the same error on FF/IE:
TypeError: this.parentNode is null

Same stack trace.

**Comment by cbwhitebu** [comment]
Also encountered: Firefox 41.0.2

paper-ripple.html.js:411:1

Doesn't happen if I set a breakpoint at the line.

Chris

**Comment by notwaldorf** [comment]
This should be fixed by the re-factoring done in https://github.com/PolymerElements/paper-ripple/pull/63. Please re-open if you can still repro this with that code
