### ISSUE TITLE
Add mixin for --paper-ripple

### ISSUE THREAD

**Issue by bendavis78** [PolymerElements/paper-ripple#37]
The docs for [paper-button](https://github.com/PolymerElements/paper-button/blob/master/paper-button.html#L58) currently suggest using `::shadow` to style the ripple. Since the `::shadow` combinator is  being deprecated, a mixin should be used instead.

**Comment by pdgago** [comment]
+1

**Comment by keanulee** [comment]
@bendavis78 @pdgago 

I can't find the paper-button docs that use `::shadow` (perhaps they were removed at some point). Generally we don't want to open unnecessary styling inputs to preserve styling encapsulation of elements. Can you give an example of what you're trying to do that requires `::shadow` or `/deep/`?

**Comment by kevinpschaaf** [comment]
Closing as outdated; the docs have been updated.

**Comment by kevinpschaaf** [comment]
The `--paper-button-ink-color` custom CSS property will control the ink color.
