### ISSUE TITLE
Problem on firing transitionend event.

### ISSUE THREAD

**Issue by motss** [PolymerElements/paper-ripple#39]
I have a simple codes here and came across an issue on `paper-button` and `paper-material` with `paper-ripple`. By right, the `_tapAction` will only be executed only after the `transitionend` event is fired. However, the output didn't quite meet my expectation:
- while mousedown and still holding, `_tapAction` executes once before any `transitionend` event is fired.
- while mouseup, multiple `transitionend` events are fired when the ripple ends its transition which led to the multiple `_tapAction` after that.

Is this a bug and why the `_tapAction` runs once while holding mousedown even there is no `transitionend` event being fired?

HTML:-
```html
<paper-button on-transitionend="_tapAction">Button</paper-button>
```
/OR
```html
<paper-material on-transitionend="_tapAction">
  <paper-ripple></paper-ripple>
  Button
</paper-material>
```

JS:-
```javascript
_tapAction: function() {
  console.log('tap...');
}
```

**Comment by kevinpschaaf** [comment]
Confirmed via http://jsbin.com/pikija/edit?html,console,output.

Agreed use of `transitionend` does not meet the purposes stated in the [docs](https://github.com/PolymerElements/paper-ripple/blob/master/paper-ripple.html#L748-L753), and seems broken for the use case of waiting until the ripple finishes animation before doing potential animation-blocking main-thread work:

> transitionend
>  Fired when the animation finishes.
> This is useful if you want to wait until the ripple animation finishes to perform some action.
