### ISSUE TITLE
Using holdDown property throws error

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-ripple#40]
https://github.com/PolymerElements/paper-ripple/blob/master/paper-ripple.html#L671

![screen shot 2015-09-30 at 3 29 13 pm]
(https://cloud.githubusercontent.com/assets/238208/10208407/14739b4c-6788-11e5-8fc9-37a013f5c393.png)

**Comment by kevinpschaaf** [comment]
Can't repro on current version by toggling `holdDown` via JS.  Can you re-open if it's still and issue with a jsBin repro?  Thanks.
