### ISSUE TITLE
Ink opacity becomes to dark...

### ISSUE THREAD

**Issue by robrez** [PolymerElements/paper-ripple#46]
_Chrome 45.02454.101m on windows 7_

If you re-parent an element containing a paper-ripple, the paper-ripple's ink opacity becomes much too dark.
![ink](https://cloud.githubusercontent.com/assets/1993389/10382299/0ce2a54c-6de8-11e5-969f-61ae4eb0754f.png)

[Here is a codepen](http://codepen.io/robrez/pen/wKeqbE?editors=100)

**Comment by samccone** [comment]
wow @robrez epic find A+

**Comment by robrez** [comment]
Hmm.. you guys have been busy :+1: 

This seems to have been fixed by something in Polymer/polymer#1.1.5

Cheers
