### ISSUE TITLE
polylint error

### ISSUE THREAD

**Issue by davidmaxwaterman** [PolymerElements/paper-ripple#57]
```
../bower_components/paper-ripple/paper-ripple.html:163:1
    Property isAttached not found in 'properties' for element 'paper-ripple'
```

paper-ripple#1.0.4

**Comment by davidmaxwaterman** [comment]
(maybe this has been fixed in the latest master)

**Comment by kevinpschaaf** [comment]
Moving to polylint issue tracker; this is a bug in polylint not picking up properties inherited from `Polymer.Base`

**Comment by kevinpschaaf** [comment]
This issue was moved to PolymerLabs/polylint#97
