### ISSUE TITLE
Tiny documentation issue:  downAction

### ISSUE THREAD

**Issue by robrez** [PolymerElements/paper-ripple#61]
One of the examples in the documentation looks like this:
```
downAction: function(e) {
  this.$.ripple.downAction({x: e.x, y: e.y});
}
```

The code in `downAction` actually wants this:
```
  this.$.ripple.downAction({ detail: {x: e.x, y: e.y} });
```

**Comment by dman777** [comment]
:+1:

**Comment by kevinpschaaf** [comment]
@robrez Would you mind submitting a PR for the docs?  Thanks.

**Comment by robrez** [comment]
@kevinpschaaf submitted PR https://github.com/PolymerElements/paper-ripple/pull/71
