### ISSUE TITLE
Incorrect usage of downAction in the given example

### ISSUE THREAD

**Issue by motss** [PolymerElements/paper-ripple#81]
### Description

In the doc, the given example is as follows:

```
downAction: function(e) {
  this.$.ripple.downAction({x: e.x, y: e.y});
}
```

However, this throws `Uncaught TypeError: Cannot read property 'x' of undefined`.
According to the code, it says that the method has an `event` parameter and the values of `x` and `y` are extracted from the `event.detail`. Therefore, the usage of `downAction` should be as follows:

```
downAction: function(e) {
  this.$.ripple.downAction(e.detail);
}
```
### Expected outcome

No error occurs.
### Actual outcome

With the original usage of `downAction` given in the doc, it throws an error.
### Browsers Affected
- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [x] Edge
- [x] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
Would you be interested in submitting a PR to fix this? It would be greatly appreciated! 🍻

**Comment by motss** [comment]
@notwaldorf Already submit a PR #89 to fix this.
